---
title: "Module_3_Katie"
output: html_document
date: "2023-03-24"
---

```{r}

library(dplyr)
library(tidyr)
library(ggplot2)
library(readr) 
library(lubridate)

```


```{r}
Neon_VegRMNP_1 <-read_csv("Neon_VegRMNP_1.csv")



Neon_VegRMNP_3 <-read_csv("Neon_VegRMNP_3.csv")

Neon_VegRMNP_4 <-read_csv("Neon_VegRMNP_4.csv")

Neon_VegRMNP_5 <-read_csv("Neon_VegRMNP_5.csv")

Neon_VegRMNP_6 <-read_csv("Neon_VegRMNP_6.csv")

Neon_VegRMNP_7 <-read_csv("Neon_VegRMNP_7.csv")

Neon_VegRMNP_8 <-read_csv("Neon_VegRMNP_8.csv")

Neon_VegRMNP_9 <-read_csv("Neon_VegRMNP_9.csv")

Neon_VegRMNP_10 <-read_csv("Neon_VegRMNP_10.csv")

Neon_VegRMNP_11 <-read_csv("Neon_VegRMNP_11.csv")

Neon_VegRMNP_12 <-read_csv("Neon_VegRMNP_12.csv")

Neon_VegRMNP_13 <-read_csv("Neon_VegRMNP_13.csv")

Neon_VegRMNP_14 <-read_csv("Neon_VegRMNP_14.csv")

Neon_VegRMNP_15 <-read_csv("Neon_VegRMNP_15.csv")

Neon_VegRMNP_16 <-read_csv("Neon_VegRMNP_16.csv")

Neon_VegRMNP_17 <-read_csv("Neon_VegRMNP_17.csv")

```

```{r}
neon_veg_RMNP_TOTAL <- bind_rows(Neon_VegRMNP_1, Neon_VegRMNP_3, Neon_VegRMNP_4, Neon_VegRMNP_5, Neon_VegRMNP_6, Neon_VegRMNP_7, Neon_VegRMNP_8, Neon_VegRMNP_9, Neon_VegRMNP_10, Neon_VegRMNP_11, Neon_VegRMNP_12, Neon_VegRMNP_13, Neon_VegRMNP_14, Neon_VegRMNP_15, Neon_VegRMNP_16, Neon_VegRMNP_17)

neon_veg_RMNP_TOTAL_DAY <- neon_veg_CPER_TOTAL %>%
  mutate(day = floor_date(date, unit = "day"))

summary(neon_veg_RMNP_TOTAL_DAY)

```

```{r}

neon_veg_RMNP_TOTAL_DAY %>% 
  group_by(day) %>% 
  filter(day == "2017-09-20") %>% 
  summarize(scientificName)

```

```{r}

neon_veg_RMNP_TOTAL_DAY %>% 
  group_by(day) %>% 
  filter(day == "2017-09-20") %>% 
  ggplot(aes(x=scientificName))+
  geom_bar()

```

```{r}

neon_veg_RMNP_TOTAL_DAY %>% 
  group_by(day) %>% 
  ggplot(aes(x=maxBaseCrownDiameter))+
  geom_bar()

```

```{r}

neon_veg_RMNP_TOTAL_DAY %>% 
  group_by(day) %>%
  filter(day == "2017-09-20") %>% 
  ggplot(aes(x=maxCrownDiameter))+
  geom_histogram()


```

Figure Caption: The histogram above counts the amount of maximum crown diameter of vegetation at the site RMNP during september 2019.